version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: ride-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: ride-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ride-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  location-redis:
    image: redis:7.2
    container_name: location-redis
    ports:
      - "6380:6379"

  auth-redis:
    image: redis:7.2
    container_name: auth-redis
    ports:
      - "6379:6379"